import json
from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
from pydantic import BaseModel, Field
import sys
import os

# Add parent directory to path so it can import utils
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils import robust_invoke

class ValidationResult(BaseModel):
    passed: bool = Field(description="Whether the proposed fixes passed the quality gate")
    logs: str = Field(description="Compiler/linter logs (simulated)")

validator_prompt = ChatPromptTemplate.from_messages([
    ("system", """You are the Quality Gate Tool. Your task is to act as a strict linter and compiler.
    
You are validating the proposed fixes generated by the Remediation_Engineer_Agent.
Evaluate if the proposed diff applied to the original code results in fully valid, compilable code that adheres strictly to {target_standard}.

Original Code:
{raw_input}

Proposed Fixes:
{proposed_fixes}

Return whether the code passed, and provide detailed compiler/linter logs (especially if it failed). Be realistic. If the diffs seem to correctly resolve the reported MISRA violations, return passed=True.
"""),
    ("human", "Validate the fixes.")
])

def run_quality_gate(state: dict):
    model_name = state.get("selected_model", "gemini-2.5-flash")
    llm = ChatGoogleGenerativeAI(model=model_name, temperature=0)
    structured_llm = llm.with_structured_output(ValidationResult)
    chain = validator_prompt | structured_llm
    
    proposed_fixes_json = json.dumps(state.get("proposed_fixes", []), indent=2)
    
    result = robust_invoke(chain, {
        "raw_input": state.get("raw_input", ""),
        "target_standard": state.get("target_standard", "Standard"),
        "proposed_fixes": proposed_fixes_json
    })
    
    current_attempts = state.get("validation_attempts", 0) + 1
    
    return {
        "validation_passed": result.passed,
        "validation_logs": result.logs,
        "validation_attempts": current_attempts,
        "last_agent": "Quality_Gate_Agent"
    }
